

data:
  base_path: "data/chest_xray" 
  train_dir: "data/chest_xray/train"
  test_dir: "data/chest_xray/test"
  val_split: 0.2
  seed: 1337 

model:
  img_size: 150
  batch_size: 32
  epochs: 10
  base_model: "MobileNetV2"

output:
  model_file: "models/pneumonia_detector.keras"


mlflow:
  experiment_name: "Pneumonia-Detection-V2"
  tracking_uri: "mlruns" 