stages:
  data_prepare:
    cmd: cmd /C "cd .. && python -m src.data.prepare"
    deps:
      - ../src/data/prepare.py
      - ../data/
    outs:
      - ../artifacts/data_processed/

  train:
    cmd: cmd /C "cd .. && python -m src.training.train"
    deps:
      - ../src/training/train.py
      - ../src/training/model.py
      - ../src/data/loader.py
      - ../artifacts/data_processed/
      - ../configs/params.yaml
    outs:
      - ../artifacts/models/

  evaluate:
    cmd: cmd /C "cd .. && python -m src.training.evaluate"
    deps:
      - ../src/training/evaluate.py
      - ../src/data/loader.py
      - ../artifacts/models/
      - ../artifacts/data_processed/
    metrics:
      - ../artifacts/metrics/metrics.json:
          cache: false
