stages:
  data_prepare:
    cmd: set PYTHONPATH=.. && python -m ../src/data/prepare.py

    deps:
      - ../src/data/prepare.py
      - ../data/
    outs:
      - ../artifacts/data_processed/

  train:
    cmd: set PYTHONPATH=.. && python -m ../src/training/train.py
    deps:
      - ../src/training/train.py
      - ../src/training/model.py
      - ../src/data/loader.py
      - ../artifacts/data_processed/
      - ../configs/params.yaml
    outs:
      - ../artifacts/models/

  evaluate:
    cmd: set PYTHONPATH=.. && python -m ../src/training/evaluate.py
    deps:
      - ../src/training/evaluate.py
      - ../src/data/loader.py
      - ../artifacts/models/
      - ../artifacts/data_processed/
    metrics:
      - ../artifacts/metrics/metrics.json:
          cache: false
